### PR TITLE
Baby bugbear support

### PR DESCRIPTION
**Pull request by Eric-Chng**
Tested on personal branch (which owns baby bugbear)

If own baby bugbear, equip fam, visit arena to get equipment, equip equipment, then compare to rest of familiars to find highest weight

### CODE REVIEW

**Comment by C2Talon** [comment]
I don't have that familiar, so I'll need to see the log of the whole familiar test part, to include the modtrace, to make sure this works as it should.

**Comment by Eric-Chng** [comment]
`<html>
  <body>
    <font color="blue">c2t_hccs has taken 0 minute(s) 35.626 second(s) to 
    execute so far.</font><br><font color="blue">Checking test 5: Breed More 
    Collies</font><br><font color="blue">Currently feeling lost, so skipping 
    wanderer(s).</font><br>Putting Talk to the Hand the Left-Hand Man back 
    into terrarium...<br>Taking Gabediah the Melodramedary out of terrarium...<br><font color="blue">Running 
    pre-Breed More Collies stuff...</font><br>Wielding Fourth of May Cosplay 
    Saber...<br>Equipment changed.<br>Preference nextAdventure changed from 
    The Dire Warren to None<br>Using 1 photocopied monster...<br>Preference 
    photocopyMonster changed from ungulith to<br>Preference _photocopyUsed 
    changed from false to true<br>Preference lastAdventure changed from The 
    Dire Warren to None<br><br>[67] photocopied monster<br>Preference 
    lastEncounter changed from Configure Your Unbreakable Umbrella to ungulith<br>Encounter: 
    ungulith<br>Preference _lastCombatStarted changed from 20221101212753 to 
    20221101212818<br>Preference turtleBlessingTurns changed from 36 to 37<br>Round 
    0: Prusias wins initiative!<br>Preference _concoctionDatabaseRefreshes 
    changed from 166 to 167<br>c2t_bb macro: pickpocket;if hasskill 7291;skill 
    7291;endif;<br>Round 1: Prusias executes a macro!<br>Round 1: Prusias 
    casts METEOR SHOWER!<br>You acquire an effect: Meteor Showered (1)<br>Round 
    2: Gabediah, clad in his already-intimidating Saint Patrick costume, bares 
    his teeth even more intimidatingly. Your opponent is far too intimidated 
    to attack.<br>Preference _meteorShowerUses changed from 0 to 1<br>c2t_bb 
    macro: if hasskill 7311;skill 7311;endif;<br>Round 2: Prusias executes a 
    macro!<br>Preference lastEncounter changed from ungulith to Using the Force<br>Encounter: 
    Using the Force<br>Submitting option 3 for choice 1387<br>Preference 
    _saberForceUses changed from 1 to 2<br>You acquire an item: corrupted 
    marrow<br>Finished using 1 photocopied monster.<br>Approaching pool table 
    with an aggressive stance.<br>You acquire an effect: Billiards 
    Belligerence (10)<br>Preference _poolGames changed from 0 to 1<br>Preference 
    lastAdventure changed from None to The Dire Warren<br>You lost. Boo hoo.<br>Casting 
    Empathy of the Newt 1 times...<br>You acquire an effect: Empathy (5)<br>Empathy 
    of the Newt was successfully cast.<br>Putting Gabediah the Melodramedary 
    back into terrarium...<br>Taking PVPHax the Baby Bugged Bugbear out of 
    terrarium...<br>Putting on bugged beanie...<br>Equipment changed.<br>Maximizer: 
    familiar weight<br>Maximizing...<br>540 combinations checked, best score 
    103.00<br>Wielding fish hatchet...<br>Preference 
    _concoctionDatabaseRefreshes changed from 167 to 168<br>Equipment changed.<br>Holding 
    Fourth of May Cosplay Saber...<br>Preference _concoctionDatabaseRefreshes 
    changed from 168 to 169<br>Equipment changed.<br>Putting on hewn moon-rune 
    spoon...<br>Equipment changed.<br>Putting on Beach Comb...<br>Equipment 
    changed.<br>

    

type | source | Familiar Weight | Hidden Familiar Weight | Familiar Weight Percent | Familiar Weight Cap
-- | -- | -- | -- | -- | --
Item | fish hatchet | +5.00 | = +5.00 |   |   |   |   |   |  
Item | Fourth of May Cosplay Saber | +10.00 | = +15.00 |   |   |   |   |   |  
Item | Brutal brogues | +8.00 | = +23.00 |   |   |   |   |   |  
Item | hewn moon-rune spoon | +5.00 | = +28.00 |   |   |   |   |   |  
Item | Beach Comb | +5.00 | = +33.00 |   |   |   |   |   |  
Item | bugged beanie | +10.00 | = +43.00 |   |   |   |   |   |  
Skill | Amphibian Sympathy | +5.00 | = +48.00 |   |   |   |   |   |  
Effect | Meteor Showered | +20.00 | = +68.00 |   |   |   |   |   |  
Effect | Blood Bond | +5.00 | = +73.00 |   |   |   |   |   |  
Effect | Empathy | +5.00 | = +78.00 |   |   |   |   |   |  
Effect | Leash of Linguini | +5.00 | = +83.00 |   |   |   |   |   |  
Effect | Billiards Belligerence | +5.00 | = +88.00 |   |   |   |   |   |  
Effect | Do I Know You From Somewhere? | +5.00 | = +93.00 |   |   |   |   |   |  
Effect | Hip to the Jive | +10.00 | = +103.00 |   |   |   |   |   |  


    <br>
    <br>
    </main>
    <br>
    <font color="red">Pre-Breed More Collies (familiar) test fail. Currently 
    only can complete the test in 38 turns.</font><br>choiceAdventureScript =&gt;<br>Preference 
    choiceAdventureScript changed from c2t_hccs_choices.ash to<br>betweenBattleScript 
    =&gt;<br>Preference betweenBattleScript changed from c2t_hccs_preAdv.ash to<br>afterAdventureScript 
    =&gt;<br>Preference afterAdventureScript changed from c2t_hccs_postAdv.ash 
    to<br>recoveryScript =&gt; Universal_recovery<br>Preference recoveryScript 
    changed from to Universal_recovery<br>hpAutoRecoveryItems =&gt; free 
    rest;cannelloni cocoon;visit the nuns;relaxing hot tub<br>Preference 
    hpAutoRecoveryItems changed from cannelloni cocoon;tongue of the 
    walrus;disco nap to free rest;cannelloni cocoon;visit the nuns;relaxing 
    hot tub<br>hpAutoRecovery =&gt; -0.05<br>Preference hpAutoRecovery changed 
    from 0.6 to -0.05<br>hpAutoRecoveryTarget =&gt; 0.75<br>Preference 
    hpAutoRecoveryTarget changed from 0.9 to 0.75
  </body>
</html>
`

**Comment by Eric-Chng** [comment]
Screen Shot 2022-11-01 at 2 31 09 PM
Fidoxene is active and you can see baby bugbear has 10 more weight than any other fam. 5 more if the fam were to equip stillsuit

**Comment by C2Talon** [comment]
Edited, squashed, and merged: [https://github.com/C2Talon/c2t_hccs/commit/e2d6b62b11b7fb36ac8bdb18653cc58d2d5c0a7b](https://github.com/C2Talon/c2t_hccs/commit/e2d6b62b11b7fb36ac8bdb18653cc58d2d5c0a7b)

**Pull request closed without merging**
